apiVersion: v2
name: unikorn-ui
description: A Helm chart for deploying Unikorn UI

type: application

version: 1.14.0-rc4
appVersion: 1.14.0-rc4

icon: https://assets.unikorn-cloud.org/assets/images/logos/dark-on-light/icon.png

dependencies:
- name: unikorn-common
  version: 0.1.16
  repository: https://nscaledev.github.io/uni-helm-common
